server:
  port: ${JAVA_PORT_DEFAULT:8080}

spring:
  # JDBC config
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/momo_daily_steps}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
    hikari:
      enabled: true
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
